OD Tensor 

In [1]:
import numpy as np

In [2]:
a=np.array(4)

In [3]:
print(a)

4


1d Array

In [4]:
arr=np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [7]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat)

mat.ndim




[[1 2 3]
 [4 5 6]]


2